#!/usr/bin/env bash
set -euo pipefail

VERSIONS=(8 11 17 21)
FORCE=0
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ARROW_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DESTINATION="${ARROW_ROOT}/Java-version"

while (($#)); do
  case "$1" in
    --force)
      FORCE=1
      shift
      ;;
    --destination)
      [[ $# -ge 2 ]] || { echo "--destination requires a path" >&2; exit 2; }
      DESTINATION="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

for command_name in curl python3 unzip openssl; do
  command -v "${command_name}" >/dev/null 2>&1 || {
    echo "Missing required command: ${command_name}" >&2
    exit 1
  }
done

case "$(uname -m)" in
  arm64) AZUL_ARCH="arm" ;;
  x86_64) AZUL_ARCH="x64" ;;
  *) echo "Unsupported macOS architecture: $(uname -m)" >&2; exit 1 ;;
esac

mkdir -p "${DESTINATION}" "${DESTINATION}/.cache"
DESTINATION="$(cd "${DESTINATION}" && pwd)"
CACHE_DIR="${DESTINATION}/.cache"

assert_safe_target() {
  local target="$1"
  case "${target}" in
    "${DESTINATION}"/java-*|"${CACHE_DIR}"/*) ;;
    *) echo "Refusing to modify path outside Java-version: ${target}" >&2; exit 1 ;;
  esac
}

java_home_for_target() {
  local target="$1"
  if [[ -x "${target}/Contents/Home/bin/java" ]]; then
    printf '%s\n' "${target}/Contents/Home"
  elif [[ -x "${target}/bin/java" ]]; then
    printf '%s\n' "${target}"
  else
    return 1
  fi
}

sha256_file() {
  openssl dgst -sha256 "$1" | awk '{print tolower($NF)}'
}

metadata_field() {
  local field="$1"
  python3 -c 'import json,sys; rows=json.load(sys.stdin); print(rows[0][sys.argv[1]] if rows else "")' "${field}"
}

declare -a INSTALLED_HOMES=()
for version in "${VERSIONS[@]}"; do
  target="${DESTINATION}/java-${version}"
  assert_safe_target "${target}"
  if java_home="$(java_home_for_target "${target}" 2>/dev/null)" && [[ ${FORCE} -eq 0 ]]; then
    echo "JDK ${version} already exists: ${java_home}"
    INSTALLED_HOMES+=("${java_home}")
    continue
  fi

  api_url="https://api.azul.com/metadata/v1/zulu/packages/?java_version=${version}&os=macos&arch=${AZUL_ARCH}&archive_type=zip&java_package_type=jdk&javafx_bundled=false&release_status=ga&availability_types=ca&latest=true&include_fields=sha256_hash&page=1&page_size=1"
  echo "==> Resolving Azul Zulu JDK ${version} for macOS/${AZUL_ARCH}"
  metadata="$(curl -fsSL --retry 3 "${api_url}")"
  package_name="$(printf '%s' "${metadata}" | metadata_field name)"
  download_url="$(printf '%s' "${metadata}" | metadata_field download_url)"
  expected_hash="$(printf '%s' "${metadata}" | metadata_field sha256_hash | tr '[:upper:]' '[:lower:]')"
  if [[ -z "${package_name}" || -z "${download_url}" || -z "${expected_hash}" ]]; then
    echo "Azul metadata is incomplete for JDK ${version}" >&2
    exit 1
  fi

  archive="${CACHE_DIR}/${package_name}"
  if [[ -f "${archive}" ]] && [[ "$(sha256_file "${archive}")" == "${expected_hash}" ]]; then
    echo "Using verified cached archive: ${archive}"
  else
    partial="${archive}.part"
    assert_safe_target "${partial}"
    rm -f -- "${partial}"
    echo "==> Downloading ${package_name}"
    curl -fL --retry 3 --progress-bar "${download_url}" -o "${partial}"
    actual_hash="$(sha256_file "${partial}")"
    if [[ "${actual_hash}" != "${expected_hash}" ]]; then
      rm -f -- "${partial}"
      echo "SHA256 mismatch for JDK ${version}" >&2
      exit 1
    fi
    mv -- "${partial}" "${archive}"
  fi

  extract_root="${CACHE_DIR}/extract-${version}"
  assert_safe_target "${extract_root}"
  rm -rf -- "${extract_root}"
  mkdir -p "${extract_root}"
  echo "==> Extracting JDK ${version}"
  unzip -q "${archive}" -d "${extract_root}"

  java_binary="$(find "${extract_root}" -type f -path '*/bin/java' -perm -111 -print -quit)"
  [[ -n "${java_binary}" ]] || { echo "Cannot find bin/java in ${archive}" >&2; exit 1; }
  java_home="$(cd "$(dirname "${java_binary}")/.." && pwd)"
  if [[ "${java_home}" == */Contents/Home ]]; then
    package_root="${java_home%/Contents/Home}"
  else
    package_root="${java_home}"
  fi

  if [[ -e "${target}" ]]; then
    [[ ${FORCE} -eq 1 ]] || { echo "Invalid existing target; rerun with --force: ${target}" >&2; exit 1; }
    rm -rf -- "${target}"
  fi
  mv -- "${package_root}" "${target}"
  rm -rf -- "${extract_root}"
  installed_home="$(java_home_for_target "${target}")"
  echo "Installed JDK ${version} -> ${installed_home}"
  INSTALLED_HOMES+=("${installed_home}")
done

map_path="${DESTINATION}/java-version-map.txt"
activation_path="${DESTINATION}/activate-java-versions.sh"
: >"${map_path}"
{
  printf '# Generated by scripts/install-java-versions-macos.sh\n'
  printf 'export JAVA_VERSIONS_HOME=%q\n' "${DESTINATION}"
} >"${activation_path}"

for index in "${!VERSIONS[@]}"; do
  version="${VERSIONS[$index]}"
  java_home="${INSTALLED_HOMES[$index]}"
  printf 'java-%s: %s\n' "${version}" "${java_home}" >>"${map_path}"
  printf 'export JAVA_%s_HOME=%q\n' "${version}" "${java_home}" >>"${activation_path}"
done

# shellcheck disable=SC1090
source "${activation_path}"
echo "==> Verifying installed Java versions"
for version in "${VERSIONS[@]}"; do
  variable_name="JAVA_${version}_HOME"
  java_home="${!variable_name}"
  echo "java-${version} -> ${java_home}"
  "${java_home}/bin/java" -version
  "${java_home}/bin/javac" -version
done

echo ""
echo "Installation completed. For each new terminal, run:"
echo "source Java-version/activate-java-versions.sh"
